Feature/facebook sdk blu 68
PrimarySite/facebook-sdk pull request #4
Opened 2018-11-02 14:16 UTC by ecilveks

2018-11-06 14:29 UTC, amusikal approved these changes

2018-11-06 14:34 UTC, cleder requested changes
Does the circle test pass? You probably have to enable this repository on circle CI

2018-11-07 16:08 UTC, cleder approved these changes

2018-12-07 12:54 UTC, cleder commented
Where is the PR to upstream?

2018-12-13 12:32 UTC, merged